using AdventOfCode2015;

Console.WriteLine($"Result Day 1, part 1: {Day1.Result1()}");
Console.WriteLine();
Console.WriteLine($"Result Day 1, part 2: {Day1.Result2()}");
Console.WriteLine();
Console.WriteLine($"Result Day 2, part 1: {Day2.Result1()}");
Console.WriteLine();
Console.WriteLine($"Result Day 2, part 2: {Day2.Result2()}");
Console.WriteLine();
Console.WriteLine($"Result Day 3, part 1: {Day3.Result1()}");
Console.WriteLine();
Console.WriteLine($"Result Day 3, part 2: {Day3.Result2()}");
Console.WriteLine();
//Console.WriteLine($"Result Day 4, part 1: {Day4.Result1()}");
Console.WriteLine();
//Console.WriteLine($"Result Day 4, part 2: {Day4.Result2()}");
Console.WriteLine(); 
Console.WriteLine($"Result Day 5, part 1: {Day5.Result1()}");
Console.WriteLine();
Console.WriteLine($"Result Day 5, part 2: {Day5.Result2()}");
Console.WriteLine();
var day6 = new Day6();
Console.WriteLine($"Result Day 6, part 1: {day6.Result1()}");
Console.WriteLine($"Result Day 6, part 2: {day6.Result2()}");